project_name: "helm-wrap"

before:
  hooks:
    - "go mod vendor"

builds:
  - binary: "helm-wrap"
    flags: "-trimpath"
    ldflags: "-s -w"
    mod_timestamp: "{{ $.CommitTimestamp }}"
    env:
      - "CGO_ENABLED=0"

release:
  prerelease: "false"

changelog:
  filters:
    exclude:
      - "^(refactor|style|test|docs|ci)(\\([^)]+\\))?(!)?:"
