version: 2

before:
  hooks:
    - "go mod vendor"

builds:
  - binary: "helm-wrap"
    flags: "-trimpath"
    ldflags: "-s -w"
    mod_timestamp: "{{ $.CommitTimestamp }}"
    env:
      - "CGO_ENABLED=0"
    goos:
      - linux

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
