repoServer:
  volumes:
  - name: custom-tools
    emptyDir: {}

  volumeMounts:
    - mountPath: /usr/local/bin/_helm2
      name: custom-tools
      subPath: helm2
    - mountPath: /usr/local/bin/_helm
      name: custom-tools
      subPath: helm3
    - mountPath: /usr/local/bin/helm
      name: custom-tools
      subPath: helm-wrap
    - mountPath: /usr/local/bin/helm2
      name: custom-tools
      subPath: helm-wrap
    - mountPath: /usr/local/bin/argocd-vault-plugin
      name: custom-tools
      subPath: argocd-vault-plugin
    - mountPath: /usr/local/bin/extract-kustomize
      name: custom-tools
      subPath: extract-kustomize

  initContainers:
    - image: teejaded/argocd-tools:latest
      imagePullPolicy: Always
      name: custom-tools
      volumeMounts:
      - mountPath: /custom-tools
        name: custom-tools

  env:
    - name: "VAULT_ADDR"
      value: "https://my-vault-server"
    - name: AVP_TYPE
      value: vault
    - name: AVP_AUTH_TYPE
      value: k8s
    - name: AVP_K8S_ROLE
      value: argocd
    - name: HELMWRAP_CONFIG
      value: |-
        [
            {
                "action": "transform-values",
                "filter": "$.Kustomize",
                "command": "extract-kustomize {}"
            },
            {
                "action": "shell-exec",
                "filter": "template",
                "command": "([ ! -f kustomization.yaml ] && $HELM || ($HELM > all.yaml && kustomize build)) | argocd-vault-plugin generate -"
            },
            {
                "action": "shell-exec",
                "command": "$HELM"
            }
        ]
